"""
Trust Transformer Training Script  [FIXED v2]
===============================================
CLI entry point for training the behavioral trust transformer.

Changes vs v1:
  - Delegates to fixed train_model() which uses BCEWithLogitsLoss + pos_weight.
  - Adds --no-sanity flag to skip overfit check (useful for CI).
  - Validates data file exists before starting.
  - Reports GitHub-ready aliakarma username in example paths.

Usage:
    python model/inference/train.py \
        --config model/configs/transformer_config.json \
        --data   data/raw/behavioral_sequences.json \
        --checkpoint-dir model/checkpoints/ \
        --seed 42

    # Skip sanity check (faster, for CI):
    python model/inference/train.py --no-sanity

    # Generate data first if needed:
    python simulation/scripts/generate_behavioral_data.py --seed 42
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from model.inference.transformer_model import train_model, set_seeds


def main():
    parser = argparse.ArgumentParser(
        description="Train the IoUT behavioral trust transformer"
    )
    parser.add_argument(
        "--config",
        default="model/configs/transformer_config.json",
        help="Path to transformer config JSON",
    )
    parser.add_argument(
        "--data",
        default="data/raw/behavioral_sequences.json",
        help="Path to behavioral sequences JSON (generated by generate_behavioral_data.py)",
    )
    parser.add_argument(
        "--checkpoint-dir",
        default="model/checkpoints/",
        help="Directory to save model checkpoints",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility",
    )
    parser.add_argument(
        "--no-sanity",
        action="store_true",
        help="Skip the overfit sanity check (faster; use for CI)",
    )
    args = parser.parse_args()

    # ── Pre-flight checks ─────────────────────────────────────────────────
    print("=== IoUT Trust Transformer Training [v2 — FIXED] ===")
    print(f"  Config:          {args.config}")
    print(f"  Data:            {args.data}")
    print(f"  Checkpoint dir:  {args.checkpoint_dir}")
    print(f"  Seed:            {args.seed}")
    print(f"  Sanity check:    {'disabled' if args.no_sanity else 'enabled'}")
    print()

    if not os.path.exists(args.config):
        print(f"ERROR: Config not found: {args.config}")
        sys.exit(1)

    if not os.path.exists(args.data):
        print(f"ERROR: Data file not found: {args.data}")
        print("Generate data first:")
        print("  python simulation/scripts/generate_behavioral_data.py --seed 42")
        sys.exit(1)

    # Set seed before anything else
    set_seeds(args.seed)

    # ── Train ─────────────────────────────────────────────────────────────
    model = train_model(
        config_path=args.config,
        data_path=args.data,
        checkpoint_dir=args.checkpoint_dir,
        verbose=True,
        run_sanity=not args.no_sanity,
    )

    print(f"Training complete.")
    print(f"Best model saved to: {os.path.join(args.checkpoint_dir, 'best_model.pt')}")
    print()
    print("To run inference:")
    print(
        f"  python model/inference/infer.py "
        f"--checkpoint {os.path.join(args.checkpoint_dir, 'best_model.pt')} "
        f"--sequences data/sample/sample_sequences.json"
    )


if __name__ == "__main__":
    main()
